### ISSUE TITLE
Add plotting to GUI

### ISSUE THREAD

**Issue by marioblm** [cv7l1/Audiofy#17]
Implement plotting of audio data using a Dear ImGui widget (like https://github.com/soulthreads/imgui-plot)

**Comment by jhauter** [comment]
Added wave form plot. Values should be rounded, needs controls: https://github.com/cv7l1/Audiofy/commit/76c111abee4bd8eaec7773edceb4fe95cc934c0e

**Comment by jhauter** [comment]
closed
